name: Build and deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.CI_REGISTRY }}/${{ github.repository }} .
          docker push ${{ secrets.CI_REGISTRY }}/${{ github.repository }}
  deploy:
    runs-on: ubuntu-latest
    container: docker:latest
    needs: build # depend on build job
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Pull and run Docker image
        run: |
          docker pull ${{ secrets.CI_REGISTRY }}/${{ github.repository }}
          docker container rm -f demo || true
          docker run -d -p 8093:80 --name demo --restart unless-stopped ${{ secrets.CI_REGISTRY }}/${{ github.repository }}